# API 설정
api:
  app_key: "demo_key"
  app_secret: "demo_secret"
  account_number: "demo_account"
  account_code: "demo_code"
  demo_mode: true

# 거래 설정
trading:
  max_position_size: 0.1 # 전체 자본 대비 최대 포지션 크기
  max_daily_loss: 0.02 # 일일 최대 손실 한도
  stop_loss_pct: 0.05 # 기본 손절 비율
  volatility_lookback: 20 # 변동성 계산 기간
  max_stock_ratio: 0.1 # 종목당 최대 포지션 비중
  max_investment_ratio: 0.2 # 총 투자 비중 (예: 20%)
  loss_cut_ratio: 0.02 # 기본 손절 비율 (예: 2%)
  profit_cut_ratio: 0.05 # 기본 익절 비율 (예: 5%)
  max_stock_count: 3 # 최대 보유 종목 수
  max_hold_days: 3 # 최대 보유 일수

# 알림 설정
notifications:
  telegram:
    enabled: false
    token: ""
    chat_id: ""

  email:
    enabled: false
    sender: ""
    recipient: ""
    smtp_server: ""
    smtp_port: 587
    username: ""
    password: ""

# 로깅 설정
logging:
  level: "INFO"
  file: "logs/auto_trade.log"
  max_size: 10485760 # 10MB
  backup_count: 5

# 백테스팅 설정
backtesting:
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  initial_capital: 100000000 # 1억원
  commission: 0.00015 # 0.015%
  slippage: 0.0001 # 0.01%

# 스크리닝 설정
screening:
  min_market_cap: 100000000000 # 1000억원
  min_volume: 100000 # 일일 거래량
  min_volatility: 0.01 # 최소 변동성
  max_volatility: 0.5 # 최대 변동성
  min_price: 1000 # 최소 주가
  max_price: 1000000 # 최대 주가
  momentum_days: 3 # 모멘텀 확인 기간
  min_gap_up: 0.02 # 최소 갭업 비율
  min_volume_ratio: 2.5 # 최소 거래량 증가 비율
  min_amount_ratio: 3.0 # 최소 거래대금 증가 비율
  min_ma5_ratio: 0.03 # 5일 이동평균선 이격도 최소 비율
